### ISSUE TITLE
webpacker on docker-compose

### ISSUE THREAD

**Issue by x1wins** [x1wins/CW-OVP#88]
```
  webpacker:
    <<: *app_base
    command: ./bin/webpack-dev-server < echo 'y'
    env_file:
      - .env.dev.docker.compose
      - .env.dev.s3
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    tty: false
    stdin_open: false
    ports:
      - '3035:3035'
```

and there is compatibility issue https://github.com/rails/rails/issues/43062
